#!/usr/bin/env node
import { rmSync, readFileSync, writeFileSync, symlinkSync, mkdirSync, globSync } from 'node:fs'
import { join, basename, dirname, resolve } from 'node:path'

import * as commonmark from 'commonmark'
import grayMatter from 'gray-matter'
import ejs from 'ejs'

// TODO: Implement posts.
// TODO: Implement license pages.
// TODO: Implement plain-text license downloads.

rmSync('site', { recursive: true, force: true })
mkdirSync('site')

const templates = {}
for (const file of globSync('templates/*.ejs')) {
  const base = basename(file, '.ejs')
  templates[base] = ejs.compile(readFileSync(file, 'utf8'), { filename: file })
}

for (const file of globSync('pages/**/*.md')) {
  const base = basename(file, '.md')
  const { content, data: frontMatter } = grayMatter(readFileSync(file, 'utf8'))
  const rendered = markdown(content)
  writeFileSync(join('site', base + '.html'),
    templates.page(Object.assign({ content: rendered }, frontMatter))
  )
}

const slugs = {
  'countdown': 'Countdown',
  'defensive': 'Defensive',
  'free-trial': 'Free Trial',
  'internal-use': 'Internal Use',
  'noncommercial': 'NonCommercial',
  'perimeter': 'Perimeter',
  'shield': 'Shield',
  'small-business': 'Small Business',
  'strict': 'Strict'
}

for (const file of globSync('licenses/**/*.txt')) {
  const version = basename(file, '.txt')
  const slug = basename(dirname(file))
  const plain = readFileSync(file, 'utf8')
  const html = markdown(plain)
  mkdirSync(join('site', 'licenses', slug), { recursive: true })
  writeFileSync(
    join('site', 'licenses', slug, `${version}.html`),
    templates.license(Object.assign({
      name: slugs[slug],
      slug,
      version,
      html
    }))
  )
  symlinkSync(
    resolve(file),
    resolve(join('site', 'licenses', slug, `${version}.txt`))
  )
}

for (const file of globSync('images/**/*.png')) {
  const base = basename(file)
  symlinkSync(resolve(file), resolve(join('site', base)))
}

symlinkSync(resolve('./styles.css'), resolve('./site/styles.css'))

function markdown (source) {
  const reader = new commonmark.Parser()
  const writer = new commonmark.HtmlRenderer({ safe: false })
  return writer.render(reader.parse(source))
}
